### PR TITLE
Add updated voodol2cgoodix

### LINKED ISSUE #22: Update VoodooI2CGoodix to 0.4.0 to fix double click, right click issues
Howdy, VoodooI2C Goodix 0.4.0 was recently released, including double click support, better right click support, and less phantom releases while dragging. It's a joy to use an feels much more natural.

Please update the kext you ship, test, and report back if it works!

https://github.com/lazd/VoodooI2CGoodix/releases/tag/v0.4.0

### PR DESCRIPTION
**Pull request by jibsaram**
- Resolves #22 

## Changes
- Bumps included VoodooI2CGoodix to v0.4.0
- ~~Bumps included VoodooI2C to v2.8~~

All credits and a _huge_ thanks to @lazd and @THEDEVIOUS1 for their continued hard work on supporting these wonderful little devices.

### CODE REVIEW

**Comment by lazd** [comment]
The VoodooI2CGoodix bump looks proper, but I can't speak to the VoodooI2C bump -- this is only tested with VoodooI2C 2.3 on my machine, I haven't tested the latest. Theoretically, it should work, but I'd feel more comfortable merging this if someone has!

**Comment by jibsaram** [comment]
Oh shucks, really. I checked out your repository and read through [its installation steps](https://github.com/lazd/VoodooI2CGoodix/tree/v0.4.0#installation), I guess the note on updating to the latest version isn't strictly necessary? I can remove the VoodooI2C version bump if that makes more sense.

**Comment by lazd** [comment]
Yeah, I'd say just update the `VoodooI2CGoodix` kext in this PR since it's not required to use the latest `VoodooI2C`

**Comment by jibsaram** [comment]
@lazd apologies for the slight delay, it's a busy season for me. I've just reverted the VoodooI2C version bump, as suggested! I'll go ahead and merge this, with my thanks to you for all your hard work! I hope some Pocket 2 owners out there will be able to make good use of this :).

**Pull request merged**
